import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sadekur Rahman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/image/me.png" />
      </head>
      <body className={inter.className}>
        <Navbar />

        <div className="min-h-[calc(100vh-80px)]">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
